name: SBOM & Vulnerability Scan
on:
  push: { branches: ['**'] }
  schedule: [{ cron: '11 4 * * *' }]
  workflow_dispatch: {}
permissions: { contents: read, security-events: write }
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: anchore/sbom-action@v0
        with: { output-file: sbom.spdx.json, upload-artifact: true }
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-repo.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-repo.sarif }
  codeql:
    uses: github/codeql-action/init@v3
    with: { languages: 'go,javascript' }
    secrets: inherit
